<ips:template parameters="" />


<div class="ipsMessage ipsMessage_success">
	Congratulations on installing <a href="https://github.com/GaalexxC/IPS-Application-Boilerplate" target="_blank">IPS Application Boilerplate</a>. You can start developing with our application skeleton right away. For guides and tips see the <a href="https://invisioncommunity.com/developers/docs/development/" target="_blank">Developer Documentation</a> at IPS
</div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>